# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: master.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'master.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\nLogRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08LogReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x08LogTuple\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x07\x41llLogs\x12\x17\n\x04logs\x18\x01 \x03(\x0b\x32\t.LogTuple2\x87\x01\n\x06Logger\x12&\n\nReceiveLog\x12\x0b.LogRequest\x1a\t.LogReply\"\x00\x12#\n\x07SendLog\x12\x0b.LogRequest\x1a\t.LogReply\"\x00\x12\x30\n\nGetAllLogs\x12\x16.google.protobuf.Empty\x1a\x08.AllLogs\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=45
  _globals['_LOGREQUEST']._serialized_end=74
  _globals['_LOGREPLY']._serialized_start=76
  _globals['_LOGREPLY']._serialized_end=103
  _globals['_LOGTUPLE']._serialized_start=105
  _globals['_LOGTUPLE']._serialized_end=144
  _globals['_ALLLOGS']._serialized_start=146
  _globals['_ALLLOGS']._serialized_end=180
  _globals['_LOGGER']._serialized_start=183
  _globals['_LOGGER']._serialized_end=318
# @@protoc_insertion_point(module_scope)
