FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
RUN python -m grpc_tools.protoc \
    --proto_path=. \
    --python_out=. \
    --grpc_python_out=. \
    server.proto
EXPOSE 8082 50053
CMD ["python", "secondary.py", "--http_port", "8082", "--port", "50053"]