FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
RUN python -m grpc_tools.protoc \
    --proto_path=. \
    --python_out=. \
    --grpc_python_out=. \
    server.proto
EXPOSE 8081 50052
CMD ["python", "secondary.py", "--port", "8081", "--target_port", "50052"]